import sys
import re
import subprocess
import pandas as pd

# EXAMPLE USAGE:
# clear;python strip-many-dfs.py /home/hoppip/myrtle/sensitivity-analysis/redundant-vs-no-redundant-stores/

# Source - https://stackoverflow.com/a/3777308
# Posted by Manoj Govindan, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-03, License - CC BY-SA 4.0
def get_lines_from_file(file_name):
    """
    Opens a file, reads its contents, and returns a list of strings
    with the trailing newline characters removed.
    """
    try:
        with open(file_name, 'r', encoding='utf-8') as file:
            # .splitlines() is better than .readlines() because it 
            # automatically strips the '\n' from each string.
            return file.read().splitlines()
    except FileNotFoundError:
        return f"Error: The file '{file_name}' was not found."

def main():
    inputFolder= sys.argv[1]
    f = open("temp.txt", "w")
    subprocess.call(['ls', inputFolder],stdout=f)
    f.close()
    expNameRegex = re.compile(
            r"(\d+)x(\d+)x(\d+)(.*)(.csv)"
        )
    lines = get_lines_from_file("temp.txt")
    for line in lines:
        try:
            M_str, N_str, K_str, nada, nadanada= expNameRegex.search(line).groups()
            # kernelName=f"matmul_{M_str}x{N_str}x{K_str}_f64"
            # print(kernelName)
            filePath=f"{inputFolder}/{line}"
            subprocess.call(['python', "strip-df-to-only-timed-data.py",filePath, ""])
        except AttributeError:
            print(f"skipping {line}")
    #     fullSS=f"./myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k_ss{fullSuffix}.csv"
    #     sortedL1SS=f"./myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k_ss{sortedL1Suffix}.csv"
    #     top10File=f"./myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k{top10Suffix}.csv"
    #     requestedFile=f"./myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k{suffix}.csv"
    #     basenames.append(f"{M_str}x{N_str}x{K_str}wm-n-k")
    #     kernelNames.append(kernelName)
    #     outputFiles.append(fullSS)
    #    # topTenFiles.append(top10File)
    #     requestedFiles.append(requestedFile)
    #     subprocess.call(['python3', 'myrtle/myrtle.py', kernelName, "sflt", "placeholder.json"])
    #     f = open(top10File, "w")
    #     subprocess.call(['head', sortedL1SS, "-n", "11"],stdout=f)
    #     f.close()
        #FakeNN JSON Name,M,N,K,m,n,k,JSON Name,Space Needed in L1
        # fewerCols = pd.read_csv(top10File)
        # fewerCols = fewerCols[["FakeNN JSON Name","M","N","K","m","n","k","JSON Name","Space Needed in L1"]]
        # fewerCols.to_csv(f"./{outputFolder}/{M_str}x{N_str}x{K_str}wm-n-k{top10Suffix}.csv",index=False)

    # for (a,b) in zip(kernelNames,outputFiles):
    #     print(f'Generated SS for {a}')
    #     print(f'Myrtle Output file is {b}')
    
    # subprocess.call(['cp']+ requestedFiles+[ "-t", f"./{outputFolder}"])
    
    # # generate shell scripts for snitch compilation, verilator runs, correctness checks and data extraction
    # compileScript = open(f"./{outputFolder}/compile.sh", "w")
    # runScript = open(f"./{outputFolder}/run.sh", "w")
    # checkScript = open(f"./{outputFolder}/check.sh", "w")
    # extractScript = open(f"./{outputFolder}/extract.sh", "w")
    # scripts = [compileScript, runScript, checkScript,extractScript]
    # for s in scripts:
    #     print("#!/bin/bash", file=s)
    #     print("# This script was autogenerated by topTenFromMNK.py script inside the myrtle repo.", file=s)
    #     print("cd ..;", file=s) #export experimentDir="/repo/8x16x16";

    # for basename in basenames:
    #     theTop = f"./{outputFolder}/{basename}{suffix}.csv"
    #     print("Search Space to run with scripts is ...")
    #     subprocess.call(['ls', theTop])
    #     ss = theTop
    #     # create compile script
    #     print(f"export experimentDir=/repo/{outputFolder};",file=compileScript)
    #     print(f"bash many_gemms.sh {ss} compile no no no > ./{outputFolder}/compile-{basename}.txt;",file=compileScript)
    
    #     # create run script     
    #     print(f"export experimentDir=/repo/{outputFolder};",file=runScript)   
    #     print(f"bash many_gemms.sh {ss} check run no no > ./{outputFolder}/run-{basename}.txt;",file=runScript)
     
    #     # create check script
    #     print(f"export experimentDir=/repo/{outputFolder};",file=checkScript)
    #     print(f"bash many_gemms.sh {ss} check no no no;",file=checkScript)
      
    #     # create extract script
    #     print(f"export experimentDir=/repo/{outputFolder};",file=extractScript)
    #     print(f"bash many_gemms.sh {ss} no no no extract;",file=extractScript)
    #     print(f"python combineKernelTimesIntoSingleCSV.py {ss} $experimentDir;",file=extractScript)
       
    
    # for s in scripts:
    #     print(f"cd {outputFolder};", file=s)
        
    # compileScript.close()
    # runScript.close()
    # checkScript.close()
    # extractScript.close()

if __name__ == "__main__":
    main()