import sys
import re
import subprocess
# Source - https://stackoverflow.com/a/3777308
# Posted by Manoj Govindan, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-03, License - CC BY-SA 4.0

def get_lines_from_file(file_name):
    """
    Opens a file, reads its contents, and returns a list of strings
    with the trailing newline characters removed.
    """
    try:
        with open(file_name, 'r', encoding='utf-8') as file:
            # .splitlines() is better than .readlines() because it 
            # automatically strips the '\n' from each string.
            return file.read().splitlines()
    except FileNotFoundError:
        return f"Error: The file '{file_name}' was not found."
    
# python topTenFromMNK.py "fileWInputSizes.txt" 
# python topTenFromMNK.py "02092026InputSizes.txt" 
def main():
    print("Usage example: python topTenFromMNK.py \"fileWInputSizes.txt\" \"outputFolderName\" all")
    inputSizes = sys.argv[1]
    outputFolder = sys.argv[2]
    exhaustiveOverride = False
    if len(sys.argv) == 4:
        if sys.argv[3] == "all":
            exhaustiveOverride = True
         
    lines = get_lines_from_file(inputSizes)
    expNameRegex = re.compile(
            r"(\d+)x(\d+)x(\d+)"
        )
    kernelNames = []
    outputFiles = []
    topTenFiles = []
    basenames = []
    for line in lines:
        M_str, N_str, K_str = expNameRegex.search(line).groups()
        kernelName=f"matmul_{M_str}x{N_str}x{K_str}_f64"
        fullSS=f"./myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k_searchSpace_c_analyzed-myrtle-sflt-sorted-L1.csv"
        top10File=f"./myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k_searchSpace_L1_top_10.csv"
        basenames.append(f"{M_str}x{N_str}x{K_str}wm-n-k_searchSpace")
        kernelNames.append(kernelName)
        outputFiles.append(fullSS)
        topTenFiles.append(top10File)
        subprocess.call(['python3', 'myrtle/myrtle.py', kernelName, "sflt", "placeholder.json"])
        f = open(top10File, "w")
        subprocess.call(['head', fullSS, "-n", "11"],stdout=f)
        f.close()

    for (a,b) in zip(kernelNames,outputFiles):
        print(f'Generated SS for {a}')
        print(f'Output file is {b}')
    if exhaustiveOverride:
        subprocess.call(['cp']+ outputFiles+[ "-t", f"./{outputFolder}"])
    else:
        subprocess.call(['cp']+ topTenFiles+[ "-t", f"./{outputFolder}"])
    # generate shell scripts for snitch compilation, verilator runs, correctness checks and data extraction
    compileScript = open(f"./{outputFolder}/compile.sh", "w")
    runScript = open(f"./{outputFolder}/run.sh", "w")
    checkScript = open(f"./{outputFolder}/check.sh", "w")
    extractScript = open(f"./{outputFolder}/extract.sh", "w")
    scripts = [compileScript, runScript, checkScript,extractScript]
    for s in scripts:
        print("#!/bin/bash", file=s)
        print("# This script was autogenerated by topTenFromMNK.py script inside the myrtle repo.", file=s)
        print("cd ..;", file=s)

    for basename in basenames:
        theTop = f"./{outputFolder}/{basename}_L1_top_10.csv"
        if exhaustiveOverride:
            theTop = f"./{outputFolder}/{basename}_c_analyzed-myrtle-sflt-sorted-L1.csv"
        subprocess.call(['ls', theTop])
        ss = theTop
        print(f"bash many_gemms.sh {ss} compile no no no > ./{outputFolder}/compile-{basename}.txt;",file=compileScript)
        print(f"bash many_gemms.sh {ss} check run no no > ./{outputFolder}/run-{basename}.txt;",file=runScript)
        print(f"bash many_gemms.sh {ss} check no no no;",file=checkScript)
        print(f"bash many_gemms.sh {ss} no no no extract;",file=extractScript)
        print(f"python combineKernelTimesIntoSingleCSV.py {ss};",file=extractScript)
    
    for s in scripts:
        print(f"cd {outputFolder};", file=s)
        
    compileScript.close()
    runScript.close()
    checkScript.close()
    extractScript.close()

if __name__ == "__main__":
    main()