import sys
import re
import subprocess
import pandas as pd

# Given gemm input dimensions M,N,K, this program queries myrtle for the search space 
# specified by `suffix`` (top 10 in L1 usage by default)
# then generates the scripts to compile, run, and extract results for that search space.

# Usage: python createExperiment.py path-to-inputSize.txt outputFolder suffix
# when suffix is not provided, the search space defaults to sorted and pruned for top 10 in L1 usage
# when suffix is "all", the full searchspace is used (sorted in the dataframe by L1 usage)
# when suffix is anything else, this program tries to use the search space 
# generated by myrtle with the provided suffix. 
# Example Usage:
# python createExperiment.py "../128x128x128/input.txt" "../128x128x128" "_ss_c_rem_div_ana_pruned"
# python createExperiment.py "../16x16x16/input.txt" "../16x16x16" "_ss_c_rem_div_ana_pruned"


def gen_slurm_scripts(outputFolder,topLevelOutputFolder):
    # echo job
    slurmScript = open(f"./{outputFolder}/echo-job.slurm", "w")
    slurmScript.writelines("#!/bin/bash\n")
    slurmScript.writelines("#SBATCH --job-name=" + topLevelOutputFolder + "\n")
    slurmScript.writelines("#SBATCH --output=" + f"{topLevelOutputFolder}-stdout-sbatch.txt" + "\n")
    slurmScript.writelines("#SBATCH --error=" + f"{topLevelOutputFolder}-stderr-sbatch.txt"  + "\n")
    slurmScript.writelines("#SBATCH --nodes=1\n")
    slurmScript.writelines("#SBATCH --ntasks-per-node=1\n")
    slurmScript.writelines("#SBATCH --cpus-per-task=1\n")
    slurmScript.writelines("#SBATCH --mem=2G\n")
    print("# -------------------------------",file=slurmScript)
    print("# SETTINGS ----------------------",file=slurmScript)
    print("# -------------------------------",file=slurmScript)
    print("# This script was autogenerated by topTenFromMNK.py script inside the myrtle repo.",file=slurmScript)
    print("bash check.sh",file=slurmScript)
    print("#bash compile.sh",file=slurmScript)
    print("#bash run.sh",file=slurmScript)
    print("#bash extract.sh",file=slurmScript)
    slurmScript.close()
    # urano job
    slurmScript = open(f"./{outputFolder}/urano-job.slurm", "w")
    slurmScript.writelines("#!/bin/bash\n")
    slurmScript.writelines("#SBATCH --job-name=" + topLevelOutputFolder + "\n")
    slurmScript.writelines("#SBATCH --output=" + f"{topLevelOutputFolder}-stdout-sbatch.txt" + "\n")
    slurmScript.writelines("#SBATCH --error=" + f"{topLevelOutputFolder}-stderr-sbatch.txt"  + "\n")
    print("#SBATCH --partition=urano",file=slurmScript)
    print("#SBATCH --gres=gpu:adalov:0",file=slurmScript)
    print("#SBATCH --chdir=/home_nfs/esillars/urano",file=slurmScript)
    slurmScript.writelines("#SBATCH --nodes=1\n")
    slurmScript.writelines("#SBATCH --ntasks-per-node=1\n")
    slurmScript.writelines("#SBATCH --cpus-per-task=4\n")
    slurmScript.writelines("#SBATCH --mem=2G\n")
    print("# -------------------------------",file=slurmScript)
    print("# SETTINGS ----------------------",file=slurmScript)
    print("# -------------------------------",file=slurmScript)
    print("# This script was autogenerated by topTenFromMNK.py script inside the myrtle repo.",file=slurmScript)
    print("bash check.sh",file=slurmScript)
    print("#bash compile.sh",file=slurmScript)
    print("#bash run.sh",file=slurmScript)
    print("#bash extract.sh",file=slurmScript)
    slurmScript.close()

# Source - https://stackoverflow.com/a/3777308
# Posted by Manoj Govindan, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-03, License - CC BY-SA 4.0
def get_lines_from_file(file_name):
    """
    Opens a file, reads its contents, and returns a list of strings
    with the trailing newline characters removed.
    """
    try:
        with open(file_name, 'r', encoding='utf-8') as file:
            # .splitlines() is better than .readlines() because it 
            # automatically strips the '\n' from each string.
            return file.read().splitlines()
    except FileNotFoundError:
        raise Exception(f"Error: The file '{file_name}' was not found.")
    #125x128x125wm-n-k_ss_c_rem_div_ana_pr_sel_sflt

def main():
    inputSizes = sys.argv[1]
    outputFolder = sys.argv[2]
    fullSuffix = "_ss_c_rem_div_ana"
    sortedL1Suffix = "_c_ord_L1"
    top10Suffix = "_top10_c_L1"
    suffix = top10Suffix # by default
    timeout = 0 # by default
    if len(sys.argv) >= 4:
        if sys.argv[3] == "all":
            suffix = fullSuffix
        elif sys.argv[3] == "pad":
            suffix = "_ss_c_pad_ana"
        else:
            suffix = sys.argv[3]
    if len(sys.argv) == 5:
        timeout=int(sys.argv[4])
     
    lines = get_lines_from_file(inputSizes)
    expNameRegex = re.compile(
            r"(\d+)x(\d+)x(\d+)"
        )
    betaRegex = re.compile(
            r"beta=(\d+)"
        )
    kernelNames = []
    outputFiles = []
    topTenFiles = []
    requestedFiles = []
    basenames = []
    beta_int = int(betaRegex.search(lines[0]).groups()[0])
    for line in lines[1:]:
        M_str, N_str, K_str= expNameRegex.search(line).groups()
        kernelName=f"matmul_{M_str}x{N_str}x{K_str}_f64"
        fullSS=f"../myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k{fullSuffix}.csv"
        requestedFile=f"../myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k{suffix}.csv"
        basenames.append(f"{M_str}x{N_str}x{K_str}wm-n-k")
        kernelNames.append(kernelName)
        outputFiles.append(fullSS)
        requestedFiles.append(requestedFile)
        spmLayout = "regular"
        subprocess.call(['python3', '../myrtle/myrtle.py', kernelName, "sflt", "placeholder.json", "prune", spmLayout])
        #subprocess.call(['python3', '../myrtle/myrtle.py', kernelName, "sflt", "placeholder.json", "NoPrune", spmLayout])
        

    for (a,b) in zip(kernelNames,outputFiles):
        print(f'Generated SS for {a}')
    
    subprocess.call(['cp']+ requestedFiles+[ "-t", f"./{outputFolder}"])
    
    # generate shell scripts for snitch compilation, verilator runs, correctness checks and data extraction
    compileScript = open(f"./{outputFolder}/compile.sh", "w")
    runScript = open(f"./{outputFolder}/run.sh", "w")
    checkScript = open(f"./{outputFolder}/check.sh", "w")
    extractScript = open(f"./{outputFolder}/extract.sh", "w")
    
    scripts = [compileScript, runScript, checkScript,extractScript]
    for s in scripts:
        print("#!/bin/bash", file=s)
        print("# This script was autogenerated by generateExperiment.py script inside the myrtle repo.", file=s)
    # if the output folder is a relative path starting with "../",
    # remove this prefix when generating the scripts for the snitch repo
    if(outputFolder[0:3] == "../"):
        topLevelOutputFolder=outputFolder[3:]
    else:
        topLevelOutputFolder=outputFolder
    for basename in basenames:
        theTop = f"./{topLevelOutputFolder}/{basename}{suffix}.csv"
        ss = theTop
        # create compile script
        print("cd ..;",file=compileScript)
        print(f"export experimentDir=/repo/{topLevelOutputFolder};",file=compileScript)
        print(f"export beta={beta_int};",file=compileScript)
        layout=int(spmLayout == "optSPM")
        print(f"export spm_opt={layout};",file=compileScript)
        print(f"bash myrtle-experiments/many_gemms.sh {ss} compile no no no > ./{topLevelOutputFolder}/compile-{basename}.txt;",file=compileScript)
        print(f"cd {topLevelOutputFolder};", file=compileScript)

        # create run script 
        print("cd ..;",file=runScript)    
        print(f"export experimentDir=/repo/{topLevelOutputFolder};",file=runScript)  
        print(f"export TIMEOUT={timeout};",file=runScript)  
        print(f"bash myrtle-experiments/many_gemms.sh {ss} check run no no > ./{topLevelOutputFolder}/run-{basename}.txt;",file=runScript)
        print(f"cd {topLevelOutputFolder};", file=runScript)
     
        # create check script
        print("cd ..;",file=checkScript)
        print(f"export experimentDir=/repo/{topLevelOutputFolder};",file=checkScript)
        print(f"bash myrtle-experiments/many_gemms.sh {ss} check no no no;",file=checkScript)
        print(f"cd {topLevelOutputFolder};", file=checkScript)
      
        # create extract script
        print("cd ..;",file=extractScript)
        print(f"export experimentDir=/repo/{topLevelOutputFolder};",file=extractScript)
        print(f"#bash myrtle-experiments/many_gemms.sh {ss} no no extract;",file=extractScript)
        print(f"python myrtle-experiments/combineTilingSchemeDataIntoSingleCSV.py {ss} $experimentDir;",file=extractScript)
        print(f"cd {topLevelOutputFolder};", file=extractScript)
        
        # create slurm job files
        #gen_slurm_scripts(outputFolder,topLevelOutputFolder)
        
        
    compileScript.close()
    runScript.close()
    checkScript.close()
    extractScript.close()

if __name__ == "__main__":
    main()