import sys
import re
import subprocess
import pandas as pd
# Given matmul input dimensions M,N,K, this program queries myrtle for the search space 
# specified by `suffix`` (top 10 in L1 usage by default)
# then generates the scripts to compile, run, and extract results for that search space.

# Usage: python topTenFromMNK.py path-to-inputSize.txt outputFolder suffix
# when suffix is not provided, the search space defaults to sorted and pruned for top 10 in L1 usage
# when suffix is "all", the full searchspace is used (sorted in the dataframe by L1 usage)
# when suffix is anything else, this program tries to use the search space 
# generated by myrtle with the provided suffix. 

# Source - https://stackoverflow.com/a/3777308
# Posted by Manoj Govindan, modified by community. See post 'Timeline' for change history
# Retrieved 2026-02-03, License - CC BY-SA 4.0
def get_lines_from_file(file_name):
    """
    Opens a file, reads its contents, and returns a list of strings
    with the trailing newline characters removed.
    """
    try:
        with open(file_name, 'r', encoding='utf-8') as file:
            # .splitlines() is better than .readlines() because it 
            # automatically strips the '\n' from each string.
            return file.read().splitlines()
    except FileNotFoundError:
        return f"Error: The file '{file_name}' was not found."

#python topTenFromMNK.py "../16x16x16/input.txt" "../16x16x16" _ss_c_rem_gen
# python topTenFromMNK.py "../16x16x16-debug/input.txt" "../16x16x16-debug"    
# python topTenFromMNK.py "../128x128x128-pruned/input.txt" "../128x128x128-pruned"
# python topTenFromMNK.py "../512x512x512/input.txt" "../512x512x512"
# python topTenFromMNK.py "../32x32x32/input.txt" "../32x32x32" _ss_c_rem_gen
# python topTenFromMNK.py "../128x128x128/input.txt" "../128x128x128" _ss_c_rem_gen
def main():
    #print("Usage example: python topTenFromMNK.py \"fileWInputSizes.txt\" \"outputFolderName\" all")
    inputSizes = sys.argv[1]
    outputFolder = sys.argv[2]
    fullSuffix = "_ss_c_ana"
    sortedL1Suffix = "_c_ord_L1"
    top10Suffix = "_top10_c_L1"
    suffix = top10Suffix # by default
    if len(sys.argv) == 4:
        if sys.argv[3] == "all":
            suffix = fullSuffix
        elif sys.argv[3] == "pad":
            suffix = "_ss_c_pad_ana"
        else:
            suffix = sys.argv[3]
            
    lines = get_lines_from_file(inputSizes)
    expNameRegex = re.compile(
            r"(\d+)x(\d+)x(\d+)"
        )
    kernelNames = []
    outputFiles = []
    topTenFiles = []
    requestedFiles = []
    basenames = []
    for line in lines:
        M_str, N_str, K_str = expNameRegex.search(line).groups()
        kernelName=f"matmul_{M_str}x{N_str}x{K_str}_f64"
        fullSS=f"../myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k_ss{fullSuffix}.csv"
        sortedL1SS=f"../myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k_ss{sortedL1Suffix}.csv"
        top10File=f"../myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k{top10Suffix}.csv"
        requestedFile=f"../myrtle/out/{M_str}x{N_str}x{K_str}wm-n-k{suffix}.csv"
        basenames.append(f"{M_str}x{N_str}x{K_str}wm-n-k")
        kernelNames.append(kernelName)
        outputFiles.append(fullSS)
       # topTenFiles.append(top10File)
        requestedFiles.append(requestedFile)
        subprocess.call(['python3', '../myrtle/myrtle.py', kernelName, "sflt", "placeholder.json"])
        f = open(top10File, "w")
        subprocess.call(['head', sortedL1SS, "-n", "11"],stdout=f)
        f.close()
        #FakeNN JSON Name,M,N,K,m,n,k,JSON Name,Space Needed in L1
        # fewerCols = pd.read_csv(top10File)
        # fewerCols = fewerCols[["FakeNN JSON Name","M","N","K","m","n","k","JSON Name","Space Needed in L1"]]
        # fewerCols.to_csv(f"./{outputFolder}/{M_str}x{N_str}x{K_str}wm-n-k{top10Suffix}.csv",index=False)

    for (a,b) in zip(kernelNames,outputFiles):
        print(f'Generated SS for {a}')
        print(f'Myrtle Output file is {b}')
    
    subprocess.call(['cp']+ requestedFiles+[ "-t", f"./{outputFolder}"])
    
    # generate shell scripts for snitch compilation, verilator runs, correctness checks and data extraction
    compileScript = open(f"./{outputFolder}/compile.sh", "w")
    runScript = open(f"./{outputFolder}/run.sh", "w")
    checkScript = open(f"./{outputFolder}/check.sh", "w")
    extractScript = open(f"./{outputFolder}/extract.sh", "w")
    scripts = [compileScript, runScript, checkScript,extractScript]
    for s in scripts:
        print("#!/bin/bash", file=s)
        print("# This script was autogenerated by topTenFromMNK.py script inside the myrtle repo.", file=s)
        print("cd ..;", file=s) #export experimentDir="/repo/8x16x16";
    # if the output folder is a relative path starting with "../",
    # remove this prefix when generating the scripts for the snitch repo
    if(outputFolder[0:3] == "../"):
        topLevelOutputFolder=outputFolder[3:]
    else:
        topLevelOutputFolder=outputFolder
    for basename in basenames:
        theTop = f"./{topLevelOutputFolder}/{basename}{suffix}.csv"
        ss = theTop
        # create compile script
        print(f"export experimentDir=/repo/{topLevelOutputFolder};",file=compileScript)
        print(f"bash myrtle-experiments/many_gemms.sh {ss} compile no no no > ./{topLevelOutputFolder}/compile-{basename}.txt;",file=compileScript)
    
        # create run script     
        print(f"export experimentDir=/repo/{topLevelOutputFolder};",file=runScript)   
        print(f"bash myrtle-experiments/many_gemms.sh {ss} check run no no > ./{topLevelOutputFolder}/run-{basename}.txt;",file=runScript)
     
        # create check script
        print(f"export experimentDir=/repo/{topLevelOutputFolder};",file=checkScript)
        print(f"bash myrtle-experiments/many_gemms.sh {ss} check no no no;",file=checkScript)
      
        # create extract script
        print(f"export experimentDir=/repo/{topLevelOutputFolder};",file=extractScript)
        print(f"bash myrtle-experiments/many_gemms.sh {ss} no no extract;",file=extractScript)
        print(f"python myrtle-experiments/combineTilingSchemeDataIntoSingleCSV.py {ss} $experimentDir;",file=extractScript)
       
    
    for s in scripts:
        print(f"cd {topLevelOutputFolder};", file=s)
        
    compileScript.close()
    runScript.close()
    checkScript.close()
    extractScript.close()

if __name__ == "__main__":
    main()